GET http://localhost:3000/user/index HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTksIm5hbWUiOiLmmI7ovokiLCJlbWFpbCI6InR3Nm15Mjc5QGV4YW1wbGUub3JnIiwiaWF0IjoxNzMyODcwMDg2LCJleHAiOjE3MzM0NzQ4ODZ9.uOsuGqXoht4G-s5NkXlIxXhqS_ZzrUwWjx5sGCtXLY8

###
POST http://localhost:3000/user/create HTTP/1.1
Content-Type: application/json

{
  "name": "小满33",
  "email": "werwe88@qq.com"
}